#
# This docker-compose file runs infrastructure required to host the services.
# It is useful in debugging from Visual Studio, just run the infrastructure in Docker,
# and services from the VS.
#
version: '3'
services:
  # Rabbit MQ
  rabbit:
    image: rabbitmq:3.6-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbit
  
  # SQL Server for Linux
  sqlserver:
    image: sqlserver
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Zaq123#!
    container_name: sqlserver
